name: Build & Deploy

on:
  push:
    branches:
      #- dev
      - prod

jobs:
  deploy:
    runs-on: self-hosted

    environment:
      name: ${{ github.ref_name }}

    steps:
      - uses: actions/checkout@v4

      # IMAGE TAG
      - name: Set image tag
        run: |
          echo "IMAGE_TAG=${{ github.ref_name }}-${{ github.sha }}" >> $GITHUB_ENV

      # ENV FILE
      - name: Create .env
        run: |
          echo "${{ secrets.ENV_FILE }}" > .env

      - name: Log in to GHCR
        run: |
          echo "${{ secrets.GHCR_PAT }}" | \
          docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build image
        run: |
          docker build \
            -t ghcr.io/${{ github.repository }}:${IMAGE_TAG} .

      - name: Push image
        run: |
          docker push ghcr.io/${{ github.repository }}:${IMAGE_TAG}

      - name: Deploy
        run: |
          export IMAGE_TAG=${IMAGE_TAG}
          docker compose -f docker-compose.${{ github.ref_name }}.yml pull
          docker compose -f docker-compose.${{ github.ref_name }}.yml up -d